version: "3.9"
services:
  svc1:
    image: httpd
    ports:
      - "9000:80"  
  svc2:
    image: chowan/ecomm
    ports:
      - "9090:80"
  svc3:
    image: chowan/foodapp
    ports:
      - "8000:80"

